# Generated by Django 5.2.6 on 2026-08-23 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, help_text="Internal reference, e.g. 'batch-12 / acct-04'. Never shown to buyers.", max_length=100)),
                ('payload', models.TextField(help_text='What the buyer receives: login:password, key, or instructions. Treated as a secret — masked in list views.')),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold'), ('burned', 'Burned'), ('disabled', 'Disabled')], db_index=True, default='available', max_length=16)),
                ('reserved_until', models.DateTimeField(blank=True, null=True)),
                ('sold_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='catalog.product')),
            ],
            options={
                'ordering': ['product', 'id'],
                'indexes': [models.Index(fields=['product', 'status'], name='inventory_s_product_ec5d3b_idx')],
            },
        ),
    ]
