# Generated by Django 5.2.6 on 2026-08-23 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockitem',
            name='order_item',
            field=models.ForeignKey(blank=True, help_text='The order line this unit was assigned to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_items', to='orders.orderitem'),
        ),
    ]
