# Generated by Django 5.2.6 on 2026-08-24 01:00

from django.db import migrations, models


def free_reservations(apps, schema_editor):
    """
    Reservations no longer exist, so anything still held is just available.

    Units already sold or burned keep their status — only the held ones were
    waiting on a checkout that will never come.
    """
    StockItem = apps.get_model("inventory", "StockItem")
    StockItem.objects.filter(status="reserved").update(
        status="available", order_item=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stockitem_order_item'),
    ]

    operations = [
        migrations.RunPython(free_reservations, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='stockitem',
            name='reserved_until',
        ),
        migrations.AlterField(
            model_name='stockitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('burned', 'Burned'), ('disabled', 'Disabled')], db_index=True, default='available', max_length=16),
        ),
    ]
