# Generated by Django 5.2.6 on 2026-08-24 01:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='hold_expires_at',
        ),
    ]
