# Generated by Django 5.2.6 on 2026-08-24 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_hold_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_user_agent',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AddField(
            model_name='order',
            name='fbc',
            field=models.CharField(blank=True, max_length=255, verbose_name='Meta click id'),
        ),
        migrations.AddField(
            model_name='order',
            name='fbp',
            field=models.CharField(blank=True, max_length=128, verbose_name='Meta browser id'),
        ),
        migrations.AddField(
            model_name='order',
            name='purchase_event_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='source_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
