# Generated by Django 5.2.6 on 2026-08-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='banner_url',
            field=models.URLField(blank=True, help_text='External wide banner (16:9), shown at the top of the product page.', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='cover_url',
            field=models.URLField(blank=True, help_text='External portrait cover (3:4). Used when no image is uploaded below.', max_length=500),
        ),
    ]
