# Generated by Django 5.2.6 on 2026-08-24 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_banner_url_product_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Card-sized copy, written for you when the image is uploaded.', upload_to='products/cards/'),
        ),
    ]
